global using System;
global using System.IO;
global using System.Reflection;
global using BoneLib;
global using MelonLoader;
global using WeatherElectric.LabCam.Melon;
global using BoneLib.BoneMenu;
global using UnityEngine;
global using WeatherElectric.LabCam.Resources;
global using WeatherElectric.LabCam.Scripts;
global using MelonLoader.Utils;
global using UnityEngine.Experimental.Rendering;
global using Object = UnityEngine.Object;