global using System;
global using System.IO;
global using System.Reflection;
global using System.Threading.Tasks;
global using BoneLib;
global using MelonLoader;
global using LabCam.Melon;
global using BoneLib.BoneMenu;
global using BoneLib.BoneMenu.Elements;
global using UnityEngine;
global using LabCam.Menu;
global using LabCam.Resources;
global using LabCam.Scripts;
global using SLZ.SFX;
global using Object = UnityEngine.Object;